/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @authores rosim/Adriano
 */

public class TelaCadastro extends javax.swing.JFrame {
    private TelaLogin m;
    private String nome, confirma_senha, email, confirma_email, senha;

    /**
     * Creates new form Login
     */
   
    public TelaCadastro() {
        initComponents();
        m = new TelaLogin();
        nome = "";
        email= "";
        senha = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jTextnomeCad4 = new javax.swing.JPasswordField();
        jTextnomeCad5 = new javax.swing.JPasswordField();
        jTextnomeCad1 = new javax.swing.JTextField();
        jTextnomeCad3 = new javax.swing.JTextField();
        jTextnomeCad2 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButtonRegulamento = new javax.swing.JLabel();
        jFundoCadastro = new javax.swing.JLabel();
        jButtonConfirmaCasdastro1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jTextnomeCad4.setBorder(null);
        jPanel1.add(jTextnomeCad4);
        jTextnomeCad4.setBounds(600, 300, 360, 20);

        jTextnomeCad5.setBorder(null);
        jPanel1.add(jTextnomeCad5);
        jTextnomeCad5.setBounds(600, 230, 370, 30);

        jTextnomeCad1.setBorder(null);
        jPanel1.add(jTextnomeCad1);
        jTextnomeCad1.setBounds(600, 40, 360, 30);

        jTextnomeCad3.setBorder(null);
        jPanel1.add(jTextnomeCad3);
        jTextnomeCad3.setBounds(600, 170, 360, 20);

        jTextnomeCad2.setBorder(null);
        jPanel1.add(jTextnomeCad2);
        jTextnomeCad2.setBounds(600, 110, 360, 20);

        jCheckBox1.setSelected(true);
        jCheckBox1.setBorder(null);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(620, 350, 20, 20);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(760, 400, 230, 50);

        jButtonRegulamento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jButtonRegulamento);
        jButtonRegulamento.setBounds(670, 380, 130, 20);

        jFundoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundocadastro.png"))); // NOI18N
        jFundoCadastro.setToolTipText("");
        jPanel1.add(jFundoCadastro);
        jFundoCadastro.setBounds(0, -20, 1040, 690);

        jButtonConfirmaCasdastro1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jButtonConfirmaCasdastro1);
        jButtonConfirmaCasdastro1.setBounds(750, 410, 230, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1040, 719));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        nome = jTextnomeCad1.getText();
        email = jTextnomeCad3.getText();
        senha = jTextnomeCad4.getText();

//        nome = jTextnomeCad1.getText();
//        email = jTextnomeCad2.getText();
//        confirma_email = jTextnomeCad3.getText();
//        senha = jTextnomeCad4.getText();
//        confirma_senha = jTextnomeCad5.getText();

        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/lewis","root","");
            Statement stm = con.createStatement();

            if(stm.executeUpdate("INSERT INTO tabela_cadastro (nome, email, senha) VALUES('"+nome+"','"+email+"','"+senha+"')")!=0)
            {
                JOptionPane.showMessageDialog(null,"Cadastro realizado","Sucesso",JOptionPane.INFORMATION_MESSAGE);
                jTextnomeCad1.setText("");
                jTextnomeCad3.setText("");
                jTextnomeCad3.setText("");
//                jTextnomeCad4.setText("");
//                jTextnomeCad5.setText("");
                
                m.setVisible(true);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Erro no cadastro!!!","Erro",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(ClassNotFoundException e)
        {
            JOptionPane.showMessageDialog(null,""+e.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,""+e.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jButtonConfirmaCasdastro1;
    private javax.swing.JLabel jButtonRegulamento;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jFundoCadastro;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextnomeCad1;
    private javax.swing.JTextField jTextnomeCad2;
    private javax.swing.JTextField jTextnomeCad3;
    private javax.swing.JPasswordField jTextnomeCad4;
    private javax.swing.JPasswordField jTextnomeCad5;
    // End of variables declaration//GEN-END:variables
}
